CREATE TABLE metrics (
    name VARCHAR(255) PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    value DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);