// Code generated by reset generator. DO NOT EDIT.

package main

// Reset resets all field values of structure TestStruct to zero value
func (s *TestStruct) Reset() {
	if s == nil {
		return
	}
	s.Name = ""
	s.Age = 0
	s.Active = false
	s.Score = 0.0
	s.Tags = s.Tags[:0]
	clear(s.Data)
	if s.Pointer != nil {
		*s.Pointer = ""
	}
}

// Reset resets all field values of structure AnotherTestStruct to zero value
func (s *AnotherTestStruct) Reset() {
	if s == nil {
		return
	}
	s.ID = 0
	s.Name = ""
	s.Enabled = false
	s.Values = s.Values[:0]
	clear(s.Config)
	if s.Nested != nil {
		s.Nested.Reset()
	}
}

// Reset resets all field values of structure NestedStruct to zero value
func (s *NestedStruct) Reset() {
	if s == nil {
		return
	}
	s.Field1 = ""
	s.Field2 = 0
}
